[package]
name = "dns-parse"
version = "0.1.0"
edition = "2021"
authors = ["Eugene M"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
hex = "0.4.3"
nom = "7.1.3"
